### PR TITLE
Fix progress indicator

### PR DESCRIPTION
**Pull request by nicolaslopezj**
Orion filesystem needs the progress from 0 to 100, this package is sending it from 0 to 1.

Every other change is indentation fixes.

This was tested and its ready to publish.

### CODE REVIEW

**Comment by vsivsi** [comment]
@jorisroling  Any chance you can look this over? I literally have zero time right now...  :astonished:

**Comment by jorisroling** [comment]
Yep, no problem. Fixed it! Thanks Nicolás!

**Comment by nicolaslopezj** [comment]
Great!

**Comment by vsivsi** [comment]
Looks like this change was manually added in 0.2.2 so I'm closing this PR.

**Pull request closed without merging**
